FROM golang:alpine

WORKDIR /src
COPY go.mod go.sum main.go ./
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/go/pkg/sumdb \
    go mod download

COPY ./app ./app
COPY ./pkg ./pkg
COPY ./docs ./docs
COPY ./config.dev.yaml ./config.yaml

RUN  --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/go/pkg/sumdb \
    go install github.com/cosmtrek/air@latest

CMD air