FROM golang:alpine

WORKDIR /src
COPY go.mod go.sum ./

RUN go mod download

COPY ./app/proxy ./app/proxy
COPY ./docs ./docs 
COPY ./pkg ./pkg

RUN go install github.com/cosmtrek/air@latest

CMD air --build.cmd "go build -o /tmp/proxy ./app/proxy/main.go" --build.bin "/tmp/proxy"