FROM golang:alpine

WORKDIR /src
COPY go.mod go.sum ./

RUN go mod download

COPY ./app/grpc/user ./app/grpc/user
COPY ./pkg ./pkg

RUN go install github.com/cosmtrek/air@latest

CMD air --build.cmd "go build -o /tmp/user-grpc ./app/grpc/user/main.go" --build.bin "/tmp/user-grpc"