# Build stage
FROM golang:alpine as builder

WORKDIR /src
COPY go.mod go.sum ./

RUN go mod download

COPY ./app/grpc/user ./app/grpc/user
COPY ./pkg ./pkg

RUN CGO_ENABLED=0 go build -o /tmp/user-grpc ./app/grpc/user/main.go

# Execute stag
FROM scratch
WORKDIR /build
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /tmp/user-grpx /tmp/user-grpc
ENTRYPOINT ["/tmp/user-grpc"]