FROM golang:alpine

WORKDIR /src
COPY go.mod go.sum ./

RUN go mod download

COPY ./app/api/user ./app/api/user
COPY ./pkg ./pkg

RUN go install github.com/cosmtrek/air@latest

CMD air --build.cmd "go build -o /tmp/user-api ./app/api/user/main.go" --build.bin "/tmp/user-api"