# Build stage
FROM golang:alpine as builder

WORKDIR /src
COPY go.mod go.sum ./

RUN go mod download

COPY ./app/proxy ./app/proxy
COPY ./docs ./docs 
COPY ./pkg ./pkg

RUN CGO_ENABLED=0 go build -o /tmp/proxy ./app/proxy/main.go

# Execute stag
FROM scratch
WORKDIR /build
COPY --from=builder /tmp/proxy /tmp/proxy
ENTRYPOINT ["/tmp/proxy"]
